worker_processes 1;

events {
	worker_connections 1024;
}

http {
	include mime.types;

	upstream nodejs_clusters{
		least_conn;
		server 127.0.0.1:3001;
		server 127.0.0.1:3002;
		server 127.0.0.1:3003;
	}

	server {
		listen 80;
		server_name localhost;

		# proxy_pass is the reverse proxy which can be set in upstream
		# proxy_set_header is to set the header
		# ${host} signifies the actual client host information not the nginx server one
		
		location / {
			proxy_pass http://nodejs_clusters;
			proxy_set_header Host ${host};
			proxy_set_header X-REAL-IP ${remote_addr};
		}
	}
}